import Head from 'next/head';

import AddTodoForm from '../components/AddTodoForm';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex'>
        <section className='w-1/3 bg-gray-800 h-screen p-8'>
          <div className='mb-3'>
            <h2 className='text-3xl text-white'>Add a Todo, why dont you?</h2>
          </div>
          <AddTodoForm />
        </section>
      </div>
    </>
  );
}
