import { useState } from 'react';
import { useSession, signIn, signOut } from 'next-auth/react';

import Head from 'next/head';

import AddTodoForm from '../components/AddTodoForm';
import TodoCard from '../components/TodoCard';

export default function Home(props) {
  const [todos, setTodos] = useState(props.todos);

  const { data: session, status } = useSession();

  function addTodoHandler(todo) {
    setTodos([...todos, todo]);
  }

  if (status === 'loading') {
    return <p>Loading...</p>;
  }

  if (session) {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <div className='flex'>
          <section className='w-1/3 bg-gray-800 h-screen p-8'>
            <div className='mb-3'>
              <h2 className='text-3xl text-white'>Add a Todo, why dont you?</h2>
            </div>
            <AddTodoForm onAddTodo={addTodoHandler} />
          </section>
          <section className='w-2/3 h-screen p-8'>
            <div className='mb-3'>
              <h2 className='text-3xl text-gray-700'>Todo List</h2>
            </div>
            {todos &&
              todos.map((todo) => (
                <div className='mb-3' key={todo.id}>
                  <TodoCard todo={todo} />
                </div>
              ))}
          </section>
        </div>
      </>
    );
  }

  return (
    <>
      Not Signed in...
      <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>
  );
}

export async function getServerSideProps() {
  return {
    props: {
      todos: [
        {
          id: '1',
          todo: 'Finish todo app',
          description: 'JUST DO IT!!!',
          completed: false,
        },
        {
          id: '2',
          todo: 'Get groceries',
          description: 'Write grocery list',
          completed: false,
        },
      ],
    },
  };
}
